# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
task-defaults:
    description: "Conda Pack an environment"
    worker:
        max-run-time: 14400
        docker-image: {in-tree: conda-base}
    worker-type: b-linux
    treeherder:
        symbol: "conda-linux"
        platform: "linux x86_64"
    run:
        script: conda_pack_linux.sh
        resources:
            - scripts/linux/conda_linux_install_extras.sh
            - scripts/linux/conda_trim.sh
            - requirements.txt
            - env.yml
        toolchain-alias: "filled-by-transform: conda.py"
        toolchain-artifact: public/build/conda-linux.tar.gz

conda-linux-x86_64: {}
