# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
task-defaults:
    run:
        resources:
            - env.yml
            - requirements.txt
            - taskcluster/scripts/requirements.txt
    worker:
        max-run-time: 3600

conda-mac:
    description: "Conda dev environment (MacOS)"
    run:
        script: fetch_conda_mac.sh
        toolchain-alias: conda-mac
        toolchain-artifact: public/build/conda_env_mac.tar.gz
    fetches:
        fetch:
            - miniconda-osx
    treeherder:
        symbol: TL(conda-mac)
    worker-type: b-macos
