name: Functional tests
on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

# Restrict tests to the most recent commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test_app:
    name: Build Test Client
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.testGen.outputs.tests }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Poke at hosts
        run: cat /etc/hosts

      - name: Install build dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y $(./scripts/linux/getdeps.py -a linux/debian/control)

      - name: Compile test client
        shell: bash
        run: |
          pip3 install -r requirements.txt

          mkdir -p build/cmake
          cmake -S $(pwd) -B build/cmake
          cmake --build build/cmake -j$(nproc) --target dummyvpn
          cp ./build/cmake/tests/dummyvpn/dummyvpn build/

      - uses: actions/upload-artifact@v3
        with:
          name: test-client-${{ github.sha }}
          path: |
            build/
            !build/cmake/

  functionaltests:
    name: Functional tests
    needs:
      - build_test_app
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: test-client-${{ github.sha }}
          path: build/

      - name: Install test dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y $(./scripts/linux/getdeps.py -a linux/debian/control)
          sudo apt install firefox xvfb -y
          pip3 install -r requirements.txt
          npm ci

      - name: Check build
        shell: bash
        run: |
            chmod +x ./build/dummyvpn
            ./build/dummyvpn -v


      - name: Build addons
        shell: bash
        run: ./scripts/addon/generate_all_tests.py

      - name: Running ${{matrix.test.name}} Tests
        id: runTests
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          command: |
            export HEADLESS=yes
            export TZ=Europe/London
            mkdir -p $ARTIFACT_DIR
            xvfb-run -a npm run functionalTest -- tests/functional/testAuthenticationInBrowser.js
        env:
          ARTIFACT_DIR: ${{ runner.temp }}/artifacts
          MVPN_BIN: ./build/dummyvpn

      - name: Uploading artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: ${{matrix.test.name}} Logs
          path: ${{ runner.temp }}/artifacts
