name: Release Tests
on:
  push:
    branches:
      - main
      - "releases/**"
  # TODO: Remove this - this is a bit too heavy to run on PR.
  pull_request:
    branches:
      - main
      - "releases/**"

jobs:
  resolve-taskgraph:
    name: Resolve Taskgraph
    runs-on: ubuntu-latest
    outputs:
      linux: ${{ steps.artifacts.outputs.linux }}
      macos: ${{ steps.artifacts.outputs.macos }}
      windows: ${{ steps.artifacts.outputs.windows }}
    steps:
      - name: Fetch taskgraph
        shell: bash
        env:
          TASKGRAPH_INDEX_API: https://firefox-ci-tc.services.mozilla.com/api/index/v1/task
          ## TODO: Looking up tasks by sha only works on push to main
          #TASKGRAPH_INDEX: mozillavpn.v2.mozilla-vpn-client.branch.main.revision.${{ github.sha }}.taskgraph.decision
          TASKGRAPH_INDEX: mozillavpn.v2.mozilla-vpn-client.branch.main.latest.taskgraph.decision
        run: |
          curl -v -sSL --retry 5 --retry-all-errors --retry-max-time 180 --fail \
            ${TASKGRAPH_INDEX_API}/${TASKGRAPH_INDEX}/artifacts/public%2Ftask-graph.json | jq 'to_entries | .[].value' > task-graph.json
          echo "Found Tasks:"
          jq -r '.task_id' task-graph.json

      - name: Parse taskgraph
        id: artifacts
        shell: bash
        run: |
          echo linux=$(jq -r 'select(.label == "build-linux64/release-deb").task_id' task-graph.json) >> $GITHUB_OUTPUT
          echo macos=$(jq -r 'select(.label == "signing-macos/opt").task_id' task-graph.json) >> $GITHUB_OUTPUT
          echo windows=$(jq -r 'select(.label == "repackage-msi").task_id' task-graph.json) >> $GITHUB_OUTPUT

  linux-tests:
    needs:
      - resolve-taskgraph
    uses: ./.github/workflows/prod-test-suite.yaml
    with:
      task-id: ${{ needs.resolve-taskgraph.outputs.linux }}
      group-name: linux
      artifact-name: mozillavpn.deb
      runs-on: |
        ubuntu-20.04
        ubuntu-22.04
        ubuntu-24.04

  macos-tests:
    name: MacOS Tests
    needs:
      - resolve-taskgraph
    uses: ./.github/workflows/prod-test-suite.yaml
    with:
      task-id: ${{ needs.resolve-taskgraph.outputs.macos }}
      group-name: macos
      artifact-name: MozillaVPN.pkg
      runs-on: |
        macos-12
        macos-13
        macos-14

  windows-tests:
    name: Windows Tests
    needs:
      - resolve-taskgraph
    uses: ./.github/workflows/prod-test-suite.yaml
    with:
      task-id: ${{ needs.resolve-taskgraph.outputs.windows }}
      group-name: windows
      artifact-name: MozillaVPN.msi
      runs-on: |
        windows-2019
        windows-2022
