name: Windows Tests
on:
  push:
    branches:
      - main
      - "releases/**"
  pull_request:
    branches:
      - main
      - "releases/**"

# Restrict tests to the most recent commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test_app:
    name: Build Test Client
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install build dependencies
        shell: bash
        run: |
          pip3 install -r requirements.txt

      - name: Add msvc dev commands to PATH
        uses: ilammy/msvc-dev-cmd@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install Qt6
        run: |
          curl -L https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mozillavpn.v2.mozillavpn.cache.level-3.toolchains.v3.qt-win.latest/artifacts/public%2Fbuild%2Fqt6_win.zip -o qt6_win.zip
          unzip -q -d 3rdparty qt6_win.zip

      - name: Compile test client
        run: |
          # Force the MSVC tools to come first in the path search.
          # Works around https://github.com/ilammy/msvc-dev-cmd#name-conflicts-with-shell-bash
          export PATH=$(dirname $(which cl)):$PATH

          mkdir -p build/cmake
          cmake -S $(pwd) -B build/cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_PREFIX_PATH=$(pwd)/3rdparty/QT_OUT/lib/cmake
          cmake --build build/cmake -j$(nproc) --target dummyvpn
          cp ./build/cmake/tests/dummyvpn/dummyvpn build/
          cp -r ./build/cmake/tests/dummyvpn/addons build/addons

      - uses: actions/upload-artifact@v3
        with:
          name: test-client-${{ github.sha }}
          path: |
            build/
            !build/cmake/
